export declare const GiftCardDelivery: import("@medusajs/framework/utils").DmlEntity<import("@medusajs/framework/utils").DMLEntitySchemaBuilder<{
    id: import("@medusajs/framework/utils").PrimaryKeyModifier<string, import("@medusajs/framework/utils").IdProperty>;
    idempotency_key: import("@medusajs/framework/utils").TextProperty;
    order_id: import("@medusajs/framework/utils").TextProperty;
    order_display_id: import("@medusajs/framework/utils").NullableModifier<number, import("@medusajs/framework/utils").NumberProperty>;
    line_item_id: import("@medusajs/framework/utils").TextProperty;
    unit_index: import("@medusajs/framework/utils").NumberProperty;
    gift_card_id: import("@medusajs/framework/utils").NullableModifier<string, import("@medusajs/framework/utils").TextProperty>;
    store_credit_account_id: import("@medusajs/framework/utils").NullableModifier<string, import("@medusajs/framework/utils").TextProperty>;
    buyer_customer_id: import("@medusajs/framework/utils").NullableModifier<string, import("@medusajs/framework/utils").TextProperty>;
    buyer_email: import("@medusajs/framework/utils").TextProperty;
    delivery_mode: import("@medusajs/framework/utils").EnumProperty<["self", "recipient"]>;
    recipient_email: import("@medusajs/framework/utils").NullableModifier<string, import("@medusajs/framework/utils").TextProperty>;
    recipient_name: import("@medusajs/framework/utils").NullableModifier<string, import("@medusajs/framework/utils").TextProperty>;
    sender_name: import("@medusajs/framework/utils").NullableModifier<string, import("@medusajs/framework/utils").TextProperty>;
    anonymous: import("@medusajs/framework/utils").BooleanProperty;
    message: import("@medusajs/framework/utils").NullableModifier<string, import("@medusajs/framework/utils").TextProperty>;
    design_id: import("@medusajs/framework/utils").TextProperty;
    design_snapshot: import("@medusajs/framework/utils").JSONProperty;
    currency_code: import("@medusajs/framework/utils").TextProperty;
    face_value: import("@medusajs/framework/utils").BigNumberProperty;
    paid_amount: import("@medusajs/framework/utils").BigNumberProperty;
    timezone: import("@medusajs/framework/utils").TextProperty;
    scheduled_at: import("@medusajs/framework/utils").NullableModifier<Date, import("@medusajs/framework/utils").DateTimeProperty>;
    expires_at: import("@medusajs/framework/utils").NullableModifier<Date, import("@medusajs/framework/utils").DateTimeProperty>;
    token_hash: import("@medusajs/framework/utils").NullableModifier<string, import("@medusajs/framework/utils").TextProperty>;
    token_encrypted: import("@medusajs/framework/utils").NullableModifier<string, import("@medusajs/framework/utils").TextProperty>;
    token_version: import("@medusajs/framework/utils").NumberProperty;
    issuance_status: import("@medusajs/framework/utils").EnumProperty<["awaiting_payment", "processing", "issued", "failed", "canceled"]>;
    delivery_status: import("@medusajs/framework/utils").EnumProperty<["not_ready", "scheduled", "pending", "processing", "sent", "delivered", "failed", "dead_letter", "canceled"]>;
    attempts: import("@medusajs/framework/utils").NumberProperty;
    next_retry_at: import("@medusajs/framework/utils").NullableModifier<Date, import("@medusajs/framework/utils").DateTimeProperty>;
    processing_started_at: import("@medusajs/framework/utils").NullableModifier<Date, import("@medusajs/framework/utils").DateTimeProperty>;
    paid_at: import("@medusajs/framework/utils").NullableModifier<Date, import("@medusajs/framework/utils").DateTimeProperty>;
    issued_at: import("@medusajs/framework/utils").NullableModifier<Date, import("@medusajs/framework/utils").DateTimeProperty>;
    sent_at: import("@medusajs/framework/utils").NullableModifier<Date, import("@medusajs/framework/utils").DateTimeProperty>;
    delivered_at: import("@medusajs/framework/utils").NullableModifier<Date, import("@medusajs/framework/utils").DateTimeProperty>;
    failed_at: import("@medusajs/framework/utils").NullableModifier<Date, import("@medusajs/framework/utils").DateTimeProperty>;
    claimed_at: import("@medusajs/framework/utils").NullableModifier<Date, import("@medusajs/framework/utils").DateTimeProperty>;
    claimed_customer_id: import("@medusajs/framework/utils").NullableModifier<string, import("@medusajs/framework/utils").TextProperty>;
    first_used_at: import("@medusajs/framework/utils").NullableModifier<Date, import("@medusajs/framework/utils").DateTimeProperty>;
    exhausted_at: import("@medusajs/framework/utils").NullableModifier<Date, import("@medusajs/framework/utils").DateTimeProperty>;
    provider_message_id: import("@medusajs/framework/utils").NullableModifier<string, import("@medusajs/framework/utils").TextProperty>;
    last_error: import("@medusajs/framework/utils").NullableModifier<string, import("@medusajs/framework/utils").TextProperty>;
    fallback_sent_at: import("@medusajs/framework/utils").NullableModifier<Date, import("@medusajs/framework/utils").DateTimeProperty>;
    legacy: import("@medusajs/framework/utils").BooleanProperty;
    metadata: import("@medusajs/framework/utils").NullableModifier<Record<string, unknown>, import("@medusajs/framework/utils").JSONProperty>;
}>, "gift_card_delivery">;
