import GoogleAnalytics from '@lib/analytics/google-analytics'
import UtmCapture from '@lib/context/utm-capture'
import { getTenantThemeStyles } from '@lib/site-config/theme'
import { StorefrontSharedProviders } from '@lib/storefront-shared-providers'
import { getBaseURL } from '@lib/util/env'
import { isSiteGateEnabled } from '@lib/site-config/site-gate'
import { getCanonicalOrigin } from '@lib/util/site-url'
import type { Metadata, Viewport } from 'next'
import { Cormorant_Garamond, Inter, Manrope } from 'next/font/google'
import Script from 'next/script'
import 'styles/globals.css'

// Optional analytics — set NEXT_PUBLIC_CLARITY_PROJECT_ID and NEXT_PUBLIC_GTM_ID in .env.local
const CLARITY_PROJECT_ID = process.env.NEXT_PUBLIC_CLARITY_PROJECT_ID
const GTM_ID = process.env.NEXT_PUBLIC_GTM_ID
const GTM_ENABLED = Boolean(GTM_ID)

// Inter: cuerpo, producto, precio, formularios, checkout (contenido operativo)
const inter = Inter({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-inter',
  display: 'swap',
})

// Manrope: logo, navegación, títulos de campaña y headings grandes
const manrope = Manrope({
  subsets: ['latin'],
  weight: ['600', '700', '800'],
  variable: '--font-manrope',
  display: 'swap',
})

// Cormorant Garamond: serif editorial usada solo por el template Moda
// (.fashion-home). Define la variable global; el resto del sitio la ignora.
const cormorant = Cormorant_Garamond({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  style: ['normal', 'italic'],
  variable: '--font-fashion-serif',
  display: 'swap',
})

const SITE_TITLE = 'Mercatto'
const SITE_DESCRIPTION = 'Tienda online de Mercatto'

/**
 * Keywords que no dependen de la marca NI DEL RUBRO. La marca se antepone en
 * `generateMetadata()`.
 *
 * Acá estaba `'supermercado online'`, y esta lista es el FALLBACK de toda tienda que
 * no tenga `metadata.seo.keywords` cargadas. O sea que una pinturería servía
 * `<meta name="keywords" content="Desde el sur,tienda online,supermercado online,…">`
 * en el `<head>` de cada página (DESDEELSUR-49).
 *
 * Este boilerplate es multi-rubro —hay templates de tecnología, moda, deportes y
 * campaña, no sólo `grocery`— así que el default no puede nombrar un rubro. Una tienda
 * que quiera keywords de su vertical las carga desde el admin, que es justo la rama de
 * arriba de este `else`.
 */
const GENERIC_KEYWORDS = [
  'tienda online',
  'compras online',
  'ofertas',
  'promociones',
  'envíos a todo el país',
]

const baseMetadata: Metadata = {
  // `metadataBase` real se setea en `generateMetadata()` (que ya es async y ya
  // resuelve el tenant): acá quedaría congelado al valor de build y todos los
  // hosts emitirían URLs absolutas del sitio principal.
  metadataBase: new URL(getBaseURL()),
  manifest: '/manifest.json',
  title: {
    default: SITE_TITLE,
    template: `%s | ${SITE_TITLE}`,
  },
  description: SITE_DESCRIPTION,
  applicationName: SITE_TITLE,
  keywords: [SITE_TITLE, ...GENERIC_KEYWORDS],
  // NO va `alternates.canonical` acá. `alternates` se HEREDA: un `canonical: '/'` en el
  // root hace que toda página que no declare el suyo canonicalice a la HOME — 36 de 42
  // páginas del storefront lo hacían, y Google consolida todas en una sola URL.
  // Cada página indexable declara el suyo con `canonicalUrl()` (`lib/util/site-url.ts`).
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  // og:image / twitter:image are generated by app/opengraph-image.tsx and
  // app/twitter-image.tsx (branded 1200x630 card), so they're not set here.
  openGraph: {
    type: 'website',
    siteName: SITE_TITLE,
    // NO va `url`. `openGraph` también se hereda: un `url: '/'` acá emitía
    // `og:url = <home>` en TODAS las páginas, así que compartir una PDP mostraba la
    // preview de la home. Sin el campo, la red social usa la URL que pidió.
    locale: 'es_AR',
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
  },
  twitter: {
    card: 'summary_large_image',
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
  },
  icons: {
    icon: [
      { url: '/favicon.ico' },
      { url: '/favicon-16x16.png', sizes: '16x16', type: 'image/png' },
      { url: '/favicon-32x32.png', sizes: '32x32', type: 'image/png' },
    ],
    apple: [{ url: '/apple-touch-icon.png', sizes: '180x180', type: 'image/png' }],
  },
}

/**
 * Override the favicon with the active tenant's when on a demo, so the browser tab
 * shows the demo's icon instead of Mercatto's — y aplica el Open Graph configurado
 * desde el admin, si hay extensión SEO & GEO instalada y algo cargado.
 *
 * Cada campo del Open Graph se aplica SÓLO si viene con valor: un campo vacío no es
 * "borrá el título", es "usá el de siempre". Por eso se mergea sobre `baseMetadata`
 * campo por campo en vez de reemplazar el bloque entero, que dejaría la card muda
 * apenas alguien guarda la config con un solo campo lleno.
 */
export async function generateMetadata(): Promise<Metadata> {
  const metadata: Metadata = { ...baseMetadata }

  /**
   * `metadataBase` REQUEST-AWARE, que es lo que el comentario de `baseMetadata` viene
   * prometiendo y nadie había escrito.
   *
   * Es la base de toda URL absoluta que Next emite: `og:image`, `twitter:image` y los
   * canonicals relativos. `(main)` y `(catalogo)` ya la resolvían por su cuenta, pero
   * `(checkout)`, `(b2b)` y `(splash)` no tienen `generateMetadata` propio y heredaban
   * la constante de build. En desdeelsur eso publicó
   * `<meta name="twitter:image" content="http://localhost:9000/twitter-image?…">` en el
   * checkout — una imagen social que ninguna red puede pedir.
   *
   * `getCanonicalOrigin()` además tiene el piso anti-loopback (`canonical-base.ts`).
   */
  metadata.metadataBase = new URL(await getCanonicalOrigin())

  /**
   * Gate prendido ⇒ `noindex, nofollow`.
   *
   * `baseMetadata.robots` es `index, follow` y se HEREDA en todas las páginas. Con el
   * password gate activo eso se emitía igual, así que cada URL contestaba 200 con
   * `index, follow`, el `<title>` correcto y un cuerpo de ~120 caracteres que dice
   * "Sitio en preparación": thin content duplicado, servido con una invitación
   * explícita a indexarlo.
   *
   * Va junto con el `Disallow: /` de `robots.ts`, y por el mismo motivo: `robots.txt`
   * frena el crawl, el meta frena la indexación de lo que ya se crawleó. Los dos leen
   * `isSiteGateEnabled()`, que mira SÓLO la config y no la cookie del visitante.
   */
  if (await isSiteGateEnabled()) {
    metadata.robots = { index: false, follow: false }
  }

  try {
    const { getActiveTenant } = await import('@lib/site-config/active-tenant')
    const tenant = await getActiveTenant()
    const favicon = tenant.assets?.favicon
    if (favicon) {
      metadata.icons = { icon: [{ url: favicon }], apple: [{ url: favicon }] }
    }

    /**
     * Marca del TENANT ACTIVO, no la constante de este archivo.
     *
     * `SITE_TITLE` es Mercatto, y `title.template` lo aplica a TODAS las páginas: una
     * tienda demo emitía `<title>… | Mercatto</title>` en todo su sitio, y las páginas
     * sin metadata propia (legales, cuenta) emitían el título y la descripción de
     * Mercatto tal cual (`duplicate-title` en la auditoría). Los valores de arriba
     * quedan como último fallback: si no hay tenant resoluble, esto no corre.
     */
    const brand = tenant.name || SITE_TITLE
    const seo = tenant.metadata?.seo
    metadata.title = { default: seo?.title || brand, template: `%s | ${brand}` }
    metadata.description =
      seo?.description || tenant.metadata?.description || `Tienda online de ${brand}`
    metadata.applicationName = brand
    if (seo?.keywords?.length) metadata.keywords = seo.keywords
    else if (brand !== SITE_TITLE) metadata.keywords = [brand, ...GENERIC_KEYWORDS]
  } catch {
    // Outside request scope / no tenant: fall back to the base (Mercatto) icons,
    // title, description y keywords.
  }

  const { getOpenGraphConfig } = await import('@lib/data/open-graph')
  const og = await getOpenGraphConfig()
  if (og) {
    const title = og.title || SITE_TITLE
    const description = og.description || SITE_DESCRIPTION
    const site = og.twitter_site ? { site: og.twitter_site } : {}

    // Los dos bloques se escriben COMPLETOS y con el `type`/`card` literal en vez de
    // spreadear el de `baseMetadata`: los tipos `OpenGraph` y `Twitter` de Next son
    // uniones discriminadas por esos campos, y un spread de la unión no matchea
    // ninguna variante — falla en el build de Vercel, no acá.
    metadata.openGraph = {
      type: 'website',
      siteName: og.site_name || SITE_TITLE,
      locale: og.locale || 'es_AR',
      title,
      description,
      // La imagen configurada NO se declara acá: `app/opengraph-image.tsx` es una
      // convención de archivo de Next y le gana a `openGraph.images`, así que
      // ponerla en los dos lados emitiría dos `og:image` y las redes toman la
      // primera (la generada). Esa tarjeta lee la misma config y la usa de fondo.
    }
    metadata.twitter =
      og.twitter_card === 'summary'
        ? { card: 'summary', title, description, ...site }
        : { card: 'summary_large_image', title, description, ...site }
  }

  return metadata
}

// Pinta la UI del navegador móvil (barra de direcciones Chrome Android, barra
// de estado Safari/PWA iOS) con el color PRIMARIO del tenant activo — así una
// demo pinta el navegador con su propio color, no el verde de Mercatto.
export async function generateViewport(): Promise<Viewport> {
  let themeColor = '#2e7d32'
  try {
    const { getActiveTenant } = await import('@lib/site-config/active-tenant')
    const tenant = await getActiveTenant()
    themeColor = tenant.theme.colors.primary || themeColor
  } catch {
    // Fuera de scope de request / sin tenant: cae al verde de marca.
  }
  return {
    width: 'device-width',
    initialScale: 1,
    viewportFit: 'cover',
    themeColor,
  }
}

export default async function RootLayout(props: { children: React.ReactNode }) {
  // Inyectar CSS variables del tenant dinámicamente (cacheable)
  const themeStyles = await getTenantThemeStyles()

  return (
    <html
      data-mode='light'
      lang='es'
      style={themeStyles}
      className={`${inter.variable} ${manrope.variable} ${cormorant.variable}`}
    >
      <body>
        {GTM_ENABLED && (
          <noscript>
            <iframe
              src={`https://www.googletagmanager.com/ns.html?id=${GTM_ID}`}
              height='0'
              width='0'
              style={{ display: 'none', visibility: 'hidden' }}
              title='Google Tag Manager'
            />
          </noscript>
        )}
        {GTM_ENABLED && (
          <Script id='google-tag-manager' strategy='afterInteractive'>
            {`(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
              new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
              j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
              'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
              })(window,document,'script','dataLayer','${GTM_ID}');`}
          </Script>
        )}
        {CLARITY_PROJECT_ID && (
          <Script id='ms-clarity' strategy='afterInteractive'>
            {`(function(c,l,a,r,i,t,y){
              c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
              t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
              y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
            })(window, document, "clarity", "script", "${CLARITY_PROJECT_ID}");`}
          </Script>
        )}
        <GoogleAnalytics />
        <UtmCapture />
        {/*
          `StorefrontSharedProviders` es un Client Component wrapper que
          instancia los ports internamente (SDK, cookies stub, link localizado,
          product lookup stub, cart store) y los inyecta al provider. Se hace
          asi para no cruzar props no-serializables por el boundary RSC (el
          root layout es Server Component; `sdk` es una instancia de clase que
          no se puede serializar).
        */}
        <StorefrontSharedProviders>
          <main className='relative'>{props.children}</main>
        </StorefrontSharedProviders>
      </body>
    </html>
  )
}
