import { CreateShopByLookStepInput } from './steps/create-shop-by-look';
export type CreateShopByLookInput = CreateShopByLookStepInput;
export declare const createShopByLookWorkflow: import("@medusajs/framework/workflows-sdk").ReturnWorkflow<CreateShopByLookStepInput, {
    id: string;
    title: string;
    subtitle: string | null;
    cta_label: string | null;
    image_url: string;
    image_alt: string | null;
    is_active: boolean;
    sort_order: number;
    placement: string;
    sales_channel_ids: Record<string, unknown> | null;
    region_ids: Record<string, unknown> | null;
    metadata: Record<string, unknown> | null;
    products: {
        id: string;
        product_id: string;
        variant_id: string | null;
        pos_x: number;
        pos_y: number;
        sort_order: number;
        look: /*elided*/ any;
        created_at: Date;
        updated_at: Date;
        deleted_at: Date | null;
        look_id: string;
    }[];
    created_at: Date;
    updated_at: Date;
    deleted_at: Date | null;
}, []>;
