import { model } from '@medusajs/framework/utils';

export const GiftCardDelivery = model
  .define('gift_card_delivery', {
    id: model.id({ prefix: 'gcdelivery' }).primaryKey(),
    idempotency_key: model.text(),
    order_id: model.text(),
    order_display_id: model.number().nullable(),
    line_item_id: model.text(),
    unit_index: model.number().default(0),
    gift_card_id: model.text().nullable(),
    store_credit_account_id: model.text().nullable(),
    buyer_customer_id: model.text().nullable(),
    buyer_email: model.text(),
    delivery_mode: model.enum(['self', 'recipient']),
    recipient_email: model.text().nullable(),
    recipient_name: model.text().nullable(),
    sender_name: model.text().nullable(),
    anonymous: model.boolean().default(false),
    message: model.text().nullable(),
    design_id: model.text(),
    design_snapshot: model.json(),
    currency_code: model.text(),
    face_value: model.bigNumber(),
    paid_amount: model.bigNumber(),
    timezone: model.text(),
    scheduled_at: model.dateTime().nullable(),
    expires_at: model.dateTime().nullable(),
    token_hash: model.text().nullable(),
    token_encrypted: model.text().nullable(),
    token_version: model.number().default(1),
    issuance_status: model.enum([
      'awaiting_payment', 'processing', 'issued', 'failed', 'canceled',
    ]).default('awaiting_payment'),
    delivery_status: model.enum([
      'not_ready', 'scheduled', 'pending', 'processing', 'sent', 'delivered',
      'failed', 'dead_letter', 'canceled',
    ]).default('not_ready'),
    attempts: model.number().default(0),
    next_retry_at: model.dateTime().nullable(),
    processing_started_at: model.dateTime().nullable(),
    paid_at: model.dateTime().nullable(),
    issued_at: model.dateTime().nullable(),
    sent_at: model.dateTime().nullable(),
    delivered_at: model.dateTime().nullable(),
    failed_at: model.dateTime().nullable(),
    claimed_at: model.dateTime().nullable(),
    claimed_customer_id: model.text().nullable(),
    first_used_at: model.dateTime().nullable(),
    exhausted_at: model.dateTime().nullable(),
    provider_message_id: model.text().nullable(),
    last_error: model.text().nullable(),
    fallback_sent_at: model.dateTime().nullable(),
    legacy: model.boolean().default(false),
    metadata: model.json().nullable(),
  })
  .indexes([
    { on: ['idempotency_key'], unique: true, where: 'deleted_at IS NULL' },
    { on: ['token_hash'], unique: true, where: 'deleted_at IS NULL AND token_hash IS NOT NULL' },
    { on: ['order_id', 'line_item_id', 'unit_index'] },
    { on: ['gift_card_id'] },
    { on: ['delivery_status', 'next_retry_at'] },
    { on: ['issuance_status', 'processing_started_at'] },
  ]);
