import type { GiftCardConfigV1 } from '../../lib/gift-cards-shared';
export type GiftCardDesignRow = {
    id: string;
    public_id: string;
    name: string;
    occasion: string;
    desktop_image_url: string;
    mobile_image_url: string | null;
    text_color: string;
    content_position: string;
    active: boolean;
    sort_order: number;
    metadata: Record<string, unknown> | null;
};
export type GiftCardSettingsRow = {
    id: string;
    enabled: boolean;
    timezone: string;
    morning_time: string;
    afternoon_time: string;
    evening_time: string;
    schedule_horizon_days: number;
    default_expiry_days: number | null;
    default_design_id: string;
    max_name_length: number;
    max_message_length: number;
    retry_delays_minutes: unknown;
    fallback_to_buyer: boolean;
    balance_reminder_days: number | null;
    expiring_notice_days: number | null;
    legal_text: string | null;
    terms_url: string | null;
    merchandising_url: string | null;
};
export type GiftCardDeliveryRow = {
    id: string;
    idempotency_key: string;
    order_id: string;
    order_display_id: number | null;
    line_item_id: string;
    unit_index: number;
    gift_card_id: string | null;
    store_credit_account_id: string | null;
    buyer_customer_id: string | null;
    buyer_email: string;
    delivery_mode: 'self' | 'recipient';
    recipient_email: string | null;
    recipient_name: string | null;
    sender_name: string | null;
    anonymous: boolean;
    message: string | null;
    design_id: string;
    design_snapshot: Record<string, unknown>;
    currency_code: string;
    face_value: number;
    paid_amount: number;
    timezone: string;
    scheduled_at: Date | string | null;
    expires_at: Date | string | null;
    token_hash: string | null;
    token_encrypted: string | null;
    issuance_status: 'awaiting_payment' | 'processing' | 'issued' | 'failed' | 'canceled';
    delivery_status: 'not_ready' | 'scheduled' | 'pending' | 'processing' | 'sent' | 'delivered' | 'failed' | 'dead_letter' | 'canceled';
    attempts: number;
    next_retry_at: Date | string | null;
    processing_started_at: Date | string | null;
    issued_at: Date | string | null;
    sent_at: Date | string | null;
    delivered_at: Date | string | null;
    claimed_at: Date | string | null;
    claimed_customer_id: string | null;
    first_used_at: Date | string | null;
    exhausted_at: Date | string | null;
    provider_message_id: string | null;
    last_error: string | null;
    fallback_sent_at: Date | string | null;
    legacy?: boolean;
    metadata?: Record<string, unknown> | null;
};
export type CreateGiftCardDeliveryIntentInput = {
    idempotency_key: string;
    order_id: string;
    order_display_id?: number | null;
    line_item_id: string;
    unit_index: number;
    buyer_customer_id?: string | null;
    buyer_email: string;
    config: GiftCardConfigV1;
    design: GiftCardDesignRow;
    currency_code: string;
    face_value: number;
    paid_amount: number;
    timezone: string;
    scheduled_at?: Date | null;
    expires_at?: Date | null;
};
