import type { DatabaseExplorerTableDefinition } from './access-control';

const visible = (
  column_name: string,
  opts: {
    data_type?: string;
    masked?: boolean;
    searchable?: boolean;
    filterable?: boolean;
    sortable?: boolean;
    sensitive?: boolean;
  } = {}
) => ({
  column_name,
  data_type: opts.data_type ?? null,
  visible: true,
  masked: opts.masked ?? false,
  searchable: opts.searchable ?? false,
  filterable: opts.filterable ?? false,
  sortable: opts.sortable ?? false,
  sensitive: opts.sensitive ?? false,
});

export const DEFAULT_DATABASE_EXPLORER_TABLES: DatabaseExplorerTableDefinition[] = [
  {
    table_name: 'order',
    display_name: 'Ordenes',
    description: 'Pedidos comerciales y estado operativo.',
    enabled: true,
    show_in_visual: true,
    primary_label_column: 'display_id',
    default_sort_column: 'created_at',
    default_sort_direction: 'desc',
    columns: [
      visible('id', { searchable: true, filterable: true, sortable: true }),
      visible('display_id', { searchable: true, filterable: true, sortable: true }),
      visible('email', { masked: true, searchable: true, filterable: true, sensitive: true }),
      visible('customer_id', { searchable: true, filterable: true, sortable: true }),
      visible('status', { searchable: true, filterable: true, sortable: true }),
      visible('payment_status', { filterable: true, sortable: true }),
      visible('fulfillment_status', { filterable: true, sortable: true }),
      visible('currency_code', { filterable: true, sortable: true }),
      visible('total', { sortable: true }),
      visible('metadata'),
      visible('created_at', { filterable: true, sortable: true }),
      visible('updated_at', { sortable: true }),
    ],
  },
  {
    table_name: 'customer',
    display_name: 'Clientes',
    description: 'Clientes registrados y datos de contacto enmascarados.',
    enabled: true,
    show_in_visual: true,
    primary_label_column: 'email',
    default_sort_column: 'created_at',
    default_sort_direction: 'desc',
    columns: [
      visible('id', { searchable: true, filterable: true, sortable: true }),
      visible('email', { masked: true, searchable: true, filterable: true, sensitive: true }),
      visible('first_name', { searchable: true, filterable: true, sortable: true }),
      visible('last_name', { searchable: true, filterable: true, sortable: true }),
      visible('phone', { masked: true, searchable: true, filterable: true, sensitive: true }),
      visible('metadata'),
      visible('created_at', { filterable: true, sortable: true }),
      visible('updated_at', { sortable: true }),
    ],
  },
  {
    table_name: 'product',
    display_name: 'Productos',
    description: 'Catalogo de productos.',
    enabled: true,
    show_in_visual: true,
    primary_label_column: 'title',
    default_sort_column: 'created_at',
    default_sort_direction: 'desc',
    columns: [
      visible('id', { searchable: true, filterable: true, sortable: true }),
      visible('title', { searchable: true, filterable: true, sortable: true }),
      visible('handle', { searchable: true, filterable: true, sortable: true }),
      visible('status', { filterable: true, sortable: true }),
      visible('thumbnail'),
      visible('metadata'),
      visible('created_at', { filterable: true, sortable: true }),
      visible('updated_at', { sortable: true }),
    ],
  },
  {
    table_name: 'product_variant',
    display_name: 'Variantes',
    description: 'Variantes, SKUs y codigos de producto.',
    enabled: true,
    show_in_visual: true,
    primary_label_column: 'title',
    default_sort_column: 'created_at',
    default_sort_direction: 'desc',
    columns: [
      visible('id', { searchable: true, filterable: true, sortable: true }),
      visible('product_id', { searchable: true, filterable: true, sortable: true }),
      visible('title', { searchable: true, filterable: true, sortable: true }),
      visible('sku', { searchable: true, filterable: true, sortable: true }),
      visible('barcode', { searchable: true, filterable: true, sortable: true }),
      visible('metadata'),
      visible('created_at', { filterable: true, sortable: true }),
      visible('updated_at', { sortable: true }),
    ],
  },
  {
    table_name: 'payment_collection',
    display_name: 'Pagos',
    description: 'Colecciones de pago asociadas a ordenes y carritos.',
    enabled: true,
    show_in_visual: true,
    primary_label_column: 'id',
    default_sort_column: 'created_at',
    default_sort_direction: 'desc',
    columns: [
      visible('id', { searchable: true, filterable: true, sortable: true }),
      visible('currency_code', { filterable: true, sortable: true }),
      visible('amount', { sortable: true }),
      visible('status', { filterable: true, sortable: true }),
      visible('metadata'),
      visible('created_at', { filterable: true, sortable: true }),
      visible('updated_at', { sortable: true }),
    ],
  },
  {
    table_name: 'erp_outbox_event',
    display_name: 'ERP Outbox',
    description: 'Eventos pendientes o enviados a integraciones ERP.',
    enabled: true,
    show_in_visual: true,
    primary_label_column: 'event_key',
    default_sort_column: 'created_at',
    default_sort_direction: 'desc',
    columns: [
      visible('id', { searchable: true, filterable: true, sortable: true }),
      visible('event_type', { searchable: true, filterable: true, sortable: true }),
      visible('event_key', { searchable: true, filterable: true, sortable: true }),
      visible('aggregate_type', { filterable: true, sortable: true }),
      visible('aggregate_id', { searchable: true, filterable: true, sortable: true }),
      visible('provider', { filterable: true, sortable: true }),
      visible('status', { filterable: true, sortable: true }),
      visible('attempts', { sortable: true }),
      visible('last_error'),
      visible('created_at', { filterable: true, sortable: true }),
    ],
  },
  {
    table_name: 'erp_sync_log',
    display_name: 'ERP Logs',
    description: 'Ejecuciones de sincronizacion ERP.',
    enabled: true,
    show_in_visual: true,
    primary_label_column: 'id',
    default_sort_column: 'started_at',
    default_sort_direction: 'desc',
    columns: [
      visible('id', { searchable: true, filterable: true, sortable: true }),
      visible('type', { filterable: true, sortable: true }),
      visible('status', { filterable: true, sortable: true }),
      visible('trigger', { filterable: true, sortable: true }),
      visible('summary'),
      visible('error'),
      visible('started_at', { filterable: true, sortable: true }),
      visible('finished_at', { sortable: true }),
    ],
  },
];
