/**
 * Catálogo de variables por plantilla de email — qué datos recibe cada mail, con
 * su descripción.
 *
 * ¿Por qué existe, si el seed ya las declara? Porque la FILA de la base puede no
 * declararlas. Cualquier plantilla creada fuera del seed, o migrada desde el
 * editor visual, nace con `variables` vacío — y la pantalla del admin gatea su
 * editor de variables con `variables.length === 0`. Resultado: la pantalla se ve
 * vacía y el operador no tiene dónde ver ni tocar los valores, aunque el backend
 * sepa perfectamente cuáles son. Derivando la lista del código, una fila
 * incompleta ya no puede esconder el editor.
 *
 * NO reemplaza a las listas del seed: el seed sigue escribiendo su propia copia
 * en la fila, y esta es el respaldo. Un test cruza este catálogo contra las keys
 * de `admin/lib/email-events-catalog.ts` para que una key nueva sin variables
 * falle en CI en vez de aparecer como una pantalla vacía.
 *
 * Es DATA PURA (sin imports de `@medusajs`) para que la puedan leer las tres
 * puntas: el seed, las rutas del admin y el bundle del admin.
 */

export type EmailTemplateVariable = {
  name: string;
  description?: string;
};

export const EMAIL_TEMPLATE_VARIABLES: Record<string, EmailTemplateVariable[]> = {
  'company-register': [
    { name: 'nombre_empresa', description: 'Nombre de la empresa registrada' },
    { name: 'email', description: 'Email de contacto de la empresa' },
  ],
  'customer-register': [
    { name: 'subject', description: 'Asunto del email (usado en el <title>)' },
    { name: 'name', description: 'Nombre completo del cliente (vacío si no hay)' },
    { name: 'email', description: 'Email registrado del cliente' },
    { name: 'logo_url', description: 'URL absoluta del logo del CDE' },
    { name: 'cde_display_name', description: 'Nombre del CDE / tienda' },
    { name: 'sales_channel_name', description: 'Nombre del canal de venta' },
    { name: 'primary_color', description: 'Color primario del tenant (hex)' },
    { name: 'year', description: 'Año actual para el footer' },
  ],
  'b2b-client-approved': [
    { name: 'subject', description: 'Asunto del email (usado en el <title>)' },
    { name: 'name', description: 'Nombre del cliente (vacío si no hay)' },
    { name: 'email', description: 'Email del cliente aprobado' },
    { name: 'company_name', description: 'Nombre de la empresa del cliente' },
    { name: 'logo_url', description: 'URL absoluta del logo del CDE' },
    { name: 'cde_display_name', description: 'Nombre del CDE / organización' },
  ],
  'password-reset': [
    { name: 'subject', description: 'Asunto del email (usado en el <title>)' },
    { name: 'link_reseteo', description: 'URL de restablecimiento de contraseña' },
    { name: 'logo_url', description: 'URL absoluta del logo del CDE' },
    { name: 'cde_display_name', description: 'Nombre del CDE / tienda' },
    { name: 'sales_channel_name', description: 'Nombre del canal de venta' },
    { name: 'primary_color', description: 'Color primario del tenant (hex)' },
    { name: 'year', description: 'Año actual para el footer' },
  ],
  'order-confirmation': [
    { name: 'display_id', description: 'Número de pedido a mostrar' },
    { name: 'logo_url', description: 'URL absoluta del logo del CDE' },
    { name: 'cde_display_name', description: 'Nombre del CDE / tienda' },
    { name: 'primary_color', description: 'Color primario del tenant (hex)' },
    { name: 'primary_color_bg', description: 'Color primario con opacidad (rgba) para fondos' },
    { name: 'order_date_formatted', description: 'Fecha del pedido formateada' },
    { name: 'order_items', description: 'Array de items {title, quantity, unit_price_formatted, line_total_formatted, thumbnail, color_label, color_hex}' },
    { name: 'subtotal_formatted', description: 'Subtotal formateado' },
    { name: 'discounts', description: 'Array de descuentos {label, amount_formatted, makes_free}' },
    { name: 'shipping_display', description: 'Costo de envío a mostrar ("Gratis" o "$ x")' },
    { name: 'total', description: 'Total del pedido formateado' },
    { name: 'shipping_address_one_line', description: 'Dirección de envío en una línea' },
    { name: 'shipping_method_name', description: 'Nombre del método de envío' },
    { name: 'is_store_pickup', description: 'True cuando la orden es de retiro en tienda (gatea todo el bloque)' },
    { name: 'pickup_store', description: 'Sucursal elegida {name, address, phone, hours[], map_url}. Ausente si no se pudo leer' },
    { name: 'year', description: 'Año actual para el footer' },
  ],
  'order-ready-for-pickup': [
    { name: 'display_id', description: 'Número de pedido a mostrar' },
    { name: 'customer_name', description: 'Nombre del cliente' },
    { name: 'pickup_store', description: 'Sucursal elegida {name, address, phone, hours[], map_url}' },
    { name: 'pickup_hours', description: 'Horarios de atención ya agrupados y formateados (array de strings). Vacío si la sucursal no los tiene cargados' },
    { name: 'pickup_instructions', description: 'Qué tiene que presentar el cliente para retirar. Configurable por tienda; ausente si no se configuró' },
    { name: 'logo_url', description: 'URL absoluta del logo del CDE' },
    { name: 'cde_display_name', description: 'Nombre del CDE / tienda' },
    { name: 'primary_color', description: 'Color primario del tenant (hex)' },
    { name: 'primary_color_bg', description: 'Color primario con opacidad (rgba) para fondos' },
    { name: 'year', description: 'Año actual para el footer' },
  ],
  'order-notification-admin': [
    { name: 'display_id', description: 'Número de pedido a mostrar' },
    { name: 'logo_url', description: 'URL absoluta del logo del CDE' },
    { name: 'cde_display_name', description: 'Nombre del CDE / tienda' },
    { name: 'primary_color', description: 'Color primario del tenant (hex)' },
    { name: 'primary_color_bg', description: 'Color primario con opacidad (rgba) para fondos' },
    { name: 'order_date_formatted', description: 'Fecha del pedido formateada' },
    { name: 'customer_name', description: 'Nombre del cliente' },
    { name: 'customer_email', description: 'Email del cliente' },
    { name: 'customer_phone', description: 'Teléfono del cliente' },
    { name: 'order_items', description: 'Array de items {title, quantity, unit_price_formatted, line_total_formatted, thumbnail, color_label, color_hex}' },
    { name: 'subtotal_formatted', description: 'Subtotal formateado' },
    { name: 'discounts', description: 'Array de descuentos {label, amount_formatted, makes_free}' },
    { name: 'shipping_display', description: 'Costo de envío a mostrar ("Gratis" o "$ x")' },
    { name: 'total', description: 'Total del pedido formateado' },
    { name: 'shipping_address_one_line', description: 'Dirección de envío en una línea' },
    { name: 'shipping_method_name', description: 'Nombre del método de envío' },
    { name: 'payment_method_name', description: 'Nombre del método de pago' },
    { name: 'order_notes', description: 'Observaciones del pedido' },
    { name: 'is_store_pickup', description: 'True cuando la orden es de retiro en tienda (gatea todo el bloque)' },
    { name: 'pickup_store', description: 'Sucursal elegida {name, address, phone, hours[], map_url}. Ausente si no se pudo leer' },
    { name: 'pickup_items', description: 'Disponibilidad por línea en la sucursal elegida {title, variant_title, quantity, available, available_label, status, status_label, status_color}' },
    { name: 'pickup_has_stock_issues', description: 'True si alguna línea no llega a la cantidad pedida en esa sucursal' },
    { name: 'year', description: 'Año actual para el footer' },
  ],
  'quotation-notification-admin': [
    { name: 'subject', description: 'Asunto del email (usado en el <title>)' },
    { name: 'display_id', description: 'Número de cotización a mostrar' },
    { name: 'logo_url', description: 'URL absoluta del logo del CDE' },
    { name: 'cde_display_name', description: 'Nombre del CDE / tienda' },
    { name: 'sales_channel_name', description: 'Nombre del canal de venta' },
    { name: 'primary_color', description: 'Color primario del tenant (hex)' },
    { name: 'primary_color_bg', description: 'Color primario con opacidad (rgba) para fondos' },
    { name: 'order_date_formatted', description: 'Fecha de la cotización formateada' },
    { name: 'order_items', description: 'Array de items {title, quantity, unit_price_formatted, line_total_formatted, thumbnail}' },
    { name: 'subtotal_formatted', description: 'Subtotal formateado' },
    { name: 'discounts', description: 'Array de descuentos {label, amount_formatted, makes_free}' },
    { name: 'shipping_formatted', description: 'Envío estimado formateado' },
    { name: 'total', description: 'Total de la cotización formateado' },
    { name: 'year', description: 'Año actual para el footer' },
  ],
  'quotation-rejected-admin': [
    { name: 'subject', description: 'Asunto del email (usado en el <title>)' },
    { name: 'display_id', description: 'Número de cotización a mostrar' },
    { name: 'rejection_reason', description: 'Motivo del rechazo (opcional)' },
    { name: 'logo_url', description: 'URL absoluta del logo del CDE' },
    { name: 'cde_display_name', description: 'Nombre del CDE / tienda' },
    { name: 'sales_channel_name', description: 'Nombre del canal de venta' },
    { name: 'primary_color', description: 'Color primario del tenant (hex)' },
    { name: 'primary_color_bg', description: 'Color primario con opacidad (rgba) para fondos' },
    { name: 'order_date_formatted', description: 'Fecha de la cotización formateada' },
    { name: 'order_items', description: 'Array de items {title, quantity, unit_price_formatted, line_total_formatted, thumbnail}' },
    { name: 'subtotal_formatted', description: 'Subtotal formateado' },
    { name: 'discounts', description: 'Array de descuentos {label, amount_formatted, makes_free}' },
    { name: 'shipping_formatted', description: 'Envío estimado formateado' },
    { name: 'total', description: 'Total de la cotización formateado' },
    { name: 'year', description: 'Año actual para el footer' },
  ],
  'kit-cde-notification': [
    { name: 'subject', description: 'Asunto del email (usado en el <title>)' },
    { name: 'logo_url', description: 'URL absoluta del logo de Mercatto' },
    { name: 'cde_name', description: 'Nombre del centro de distribución' },
    { name: 'order_display_id', description: 'Número de pedido a mostrar' },
    { name: 'order_date_formatted', description: 'Fecha del pedido formateada' },
    { name: 'customer_name', description: 'Nombre del cliente' },
    { name: 'customer_email', description: 'Email del cliente' },
    { name: 'order_items', description: 'Array de items {title, quantity, unit_price_formatted, line_total_formatted, thumbnail}' },
    { name: 'order_total_formatted', description: 'Total del pedido formateado' },
    { name: 'pickup_url', description: 'URL de validación de entrega' },
    { name: 'delivery_pin', description: 'PIN de entrega (opcional)' },
    { name: 'year', description: 'Año actual para el footer' },
  ],
  'order-tracking': [
    { name: 'subject', description: 'Asunto según el hito (milestone) actual' },
    { name: 'title_main', description: 'Título principal según el hito' },
    { name: 'title_sub', description: 'Subtítulo según el hito' },
    { name: 'display_id', description: 'Número de pedido a mostrar' },
    { name: 'logo_url', description: 'URL absoluta del logo del CDE' },
    { name: 'cde_display_name', description: 'Nombre del CDE / tienda' },
    { name: 'sales_channel_name', description: 'Nombre del canal de venta' },
    { name: 'primary_color', description: 'Color primario del tenant (hex)' },
    { name: 'primary_color_bg', description: 'Color primario con opacidad (rgba) para el badge' },
    { name: 'order_date_formatted', description: 'Fecha del pedido formateada' },
    { name: 'customer_name', description: 'Nombre del cliente' },
    { name: 'shipping_name', description: 'Nombre del destinatario del envío' },
    { name: 'shipping_street', description: 'Calle y número del envío' },
    { name: 'shipping_city', description: 'Ciudad y código postal del envío' },
    { name: 'timeline_steps', description: 'Array de pasos {label, done, date_formatted, icon_url}' },
    { name: 'year', description: 'Año actual para el footer' },
  ],
  'order-cancelled': [
    { name: 'subject', description: 'Asunto del email (usado en el <title>)' },
    { name: 'display_id', description: 'Número de pedido a mostrar' },
    { name: 'customer_name', description: 'Nombre del cliente' },
    { name: 'logo_url', description: 'URL absoluta del logo del CDE' },
    { name: 'cde_display_name', description: 'Nombre del CDE / tienda' },
    { name: 'sales_channel_name', description: 'Nombre del canal de venta' },
    { name: 'primary_color', description: 'Color primario del tenant (hex)' },
    { name: 'order_date_formatted', description: 'Fecha del pedido formateada' },
    { name: 'year', description: 'Año actual para el footer' },
  ],
  'stock-sync-report': [
    { name: 'subject', description: 'Asunto del email (usado en el <title>)' },
    { name: 'status_label', description: 'Etiqueta de estado ("OK" o "Falló")' },
    { name: 'status_color', description: 'Color del estado (hex)' },
    { name: 'error_message', description: 'Mensaje de error si el sync falló' },
    { name: 'started_at', description: 'Timestamp de inicio del sync' },
    { name: 'finished_at', description: 'Timestamp de fin del sync' },
    { name: 'duration_seconds', description: 'Duración en segundos' },
    { name: 'total_crm', description: 'Total de registros en el CRM' },
    { name: 'matched', description: 'Cantidad de SKUs matcheados' },
    { name: 'updated', description: 'Levels de stock actualizados' },
    { name: 'created_levels', description: 'Levels de stock creados' },
    { name: 'not_found_count', description: 'SKUs sin variante en Medusa' },
    { name: 'affected_products_count', description: 'Productos afectados' },
    { name: 'errors_count', description: 'Cantidad de errores' },
    { name: 'location_id', description: 'ID del stock location' },
    { name: 'not_found_skus_joined', description: 'SKUs no encontrados (string unido por coma)' },
    { name: 'errors_sample', description: 'Array de errores {sku, error}' },
  ],
  'company-register-admin': [
    { name: 'subject', description: 'Asunto del email (usado en el <title>)' },
    { name: 'nombre_empresa', description: 'Nombre de la empresa registrada' },
    { name: 'email', description: 'Email de contacto de la empresa' },
    { name: 'legal_name', description: 'Razón social de la empresa (opcional)' },
    { name: 'tax_id', description: 'CUIT / Tax ID de la empresa (opcional)' },
    { name: 'logo_url', description: 'URL absoluta del logo del CDE' },
    { name: 'cde_display_name', description: 'Nombre del CDE / tienda' },
    { name: 'primary_color', description: 'Color primario del tenant (hex)' },
    { name: 'year', description: 'Año actual para el footer' },
  ],
  'corporate-register': [
    { name: 'subject', description: 'Asunto del email (usado en el <title>)' },
    { name: 'nombre_empresa', description: 'Nombre de la empresa solicitante (vacío si no hay)' },
    { name: 'email', description: 'Email de contacto de la empresa' },
    { name: 'logo_url', description: 'URL absoluta del logo del CDE' },
    { name: 'cde_display_name', description: 'Nombre del CDE / tienda' },
    { name: 'primary_color', description: 'Color primario del tenant (hex)' },
    { name: 'year', description: 'Año actual para el footer' },
  ],
  'corporate-register-admin': [
    { name: 'subject', description: 'Asunto del email (usado en el <title>)' },
    { name: 'nombre_empresa', description: 'Nombre de la empresa solicitante' },
    { name: 'email', description: 'Email de contacto de la empresa' },
    { name: 'legal_name', description: 'Razón social de la empresa (opcional)' },
    { name: 'tax_id', description: 'CUIT / Tax ID de la empresa (opcional)' },
    { name: 'email_domain', description: 'Dominio del email de la empresa (opcional)' },
    { name: 'logo_url', description: 'URL absoluta del logo del CDE' },
    { name: 'cde_display_name', description: 'Nombre del CDE / tienda' },
    { name: 'primary_color', description: 'Color primario del tenant (hex)' },
    { name: 'year', description: 'Año actual para el footer' },
  ],
  'contact-received': [
    { name: 'subject', description: 'Asunto del email (usado en el <title>)' },
    { name: 'first_name', description: 'Nombre del remitente' },
    { name: 'last_name', description: 'Apellido del remitente (opcional)' },
    { name: 'email', description: 'Email del remitente' },
    { name: 'message', description: 'Mensaje enviado por el remitente' },
    { name: 'logo_url', description: 'URL absoluta del logo del CDE' },
    { name: 'cde_display_name', description: 'Nombre del CDE / tienda' },
    { name: 'primary_color', description: 'Color primario del tenant (hex)' },
    { name: 'year', description: 'Año actual para el footer' },
  ],
  'contact-notification-admin': [
    { name: 'subject', description: 'Asunto del email (usado en el <title>)' },
    { name: 'first_name', description: 'Nombre del remitente' },
    { name: 'last_name', description: 'Apellido del remitente (opcional)' },
    { name: 'email', description: 'Email del remitente' },
    { name: 'phone', description: 'Teléfono del remitente (opcional)' },
    { name: 'message', description: 'Mensaje enviado por el remitente' },
    { name: 'logo_url', description: 'URL absoluta del logo del CDE' },
    { name: 'cde_display_name', description: 'Nombre del CDE / tienda' },
    { name: 'primary_color', description: 'Color primario del tenant (hex)' },
    { name: 'year', description: 'Año actual para el footer' },
  ],
  'cart-abandoned-1': [
    { name: 'customer_name', description: 'Nombre del cliente (vacío si no hay)' },
    { name: 'total', description: 'Total del carrito formateado' },
    { name: 'currency_code', description: 'Moneda del carrito' },
    { name: 'item_count', description: 'Cantidad de productos en el carrito' },
    { name: 'recovery_url', description: 'Link para retomar el carrito' },
  ],
  'cart-abandoned-2': [
    { name: 'customer_name', description: 'Nombre del cliente (vacío si no hay)' },
    { name: 'total', description: 'Total del carrito formateado' },
    { name: 'currency_code', description: 'Moneda del carrito' },
    { name: 'item_count', description: 'Cantidad de productos en el carrito' },
    { name: 'recovery_url', description: 'Link para retomar el carrito' },
  ],
  'cart-abandoned-3': [
    { name: 'customer_name', description: 'Nombre del cliente (vacío si no hay)' },
    { name: 'total', description: 'Total del carrito formateado' },
    { name: 'currency_code', description: 'Moneda del carrito' },
    { name: 'item_count', description: 'Cantidad de productos en el carrito' },
    { name: 'recovery_url', description: 'Link para retomar el carrito' },
  ],
  'recurring-order-created': [
    { name: 'customer_name', description: 'Nombre del cliente (vacío si no hay)' },
    { name: 'frequency_label', description: 'Frecuencia elegida (ej. "todas las semanas")' },
    { name: 'next_execution', description: 'Fecha ISO de la primera ejecución' },
    { name: 'items', description: 'Lista de items ({title, quantity})' },
    { name: 'manage_url', description: 'Link a "Mis compras recurrentes"' },
  ],
  'recurring-renewal-ready': [
    { name: 'customer_name', description: 'Nombre del cliente (vacío si no hay)' },
    { name: 'frequency_label', description: 'Frecuencia de la suscripción' },
    { name: 'savings', description: 'Ahorro por el descuento de suscripción (vacío si no hay oferta)' },
    { name: 'price_warning', description: 'Aviso de suba de precio vs la entrega anterior (política warn_over_threshold)' },
    { name: 'total', description: 'Total del carrito de renovación formateado' },
    { name: 'currency_code', description: 'Moneda' },
    { name: 'item_count', description: 'Cantidad de líneas incluidas' },
    { name: 'confirmation_url', description: 'Link para confirmar y pagar' },
    { name: 'expires_at', description: 'Fecha ISO de vencimiento del link' },
  ],
  'recurring-renewal-reminder': [
    { name: 'customer_name', description: 'Nombre del cliente (vacío si no hay)' },
    { name: 'frequency_label', description: 'Frecuencia de la suscripción' },
    { name: 'confirmation_url', description: 'Link para confirmar y pagar' },
    { name: 'expires_at', description: 'Fecha ISO de vencimiento del link' },
  ],
  'recurring-order-generated': [
    { name: 'customer_name', description: 'Nombre del cliente (vacío si no hay)' },
    { name: 'order_display_id', description: 'Número visible del pedido generado' },
    { name: 'next_execution', description: 'Fecha ISO de la próxima ejecución' },
    { name: 'manage_url', description: 'Link a "Mis compras recurrentes"' },
  ],
  'recurring-order-paused': [
    { name: 'customer_name', description: 'Nombre del cliente (vacío si no hay)' },
    { name: 'frequency_label', description: 'Frecuencia de la suscripción' },
  ],
  'recurring-order-cancelled': [
    { name: 'customer_name', description: 'Nombre del cliente (vacío si no hay)' },
    { name: 'frequency_label', description: 'Frecuencia de la suscripción' },
  ],
  'recurring-order-failed': [
    { name: 'customer_name', description: 'Nombre del cliente (vacío si no hay)' },
    { name: 'frequency_label', description: 'Frecuencia de la suscripción' },
  ],
  'recurring-order-resumed': [
    { name: 'customer_name', description: 'Nombre del cliente' },
    { name: 'next_execution', description: 'Próxima fecha prevista' },
    { name: 'manage_url', description: 'Link de autogestión' },
  ],
  'recurring-order-skipped': [
    { name: 'customer_name', description: 'Nombre del cliente' },
    { name: 'next_execution', description: 'Próxima fecha prevista' },
    { name: 'manage_url', description: 'Link de autogestión' },
  ],
  'recurring-order-updated': [
    { name: 'customer_name', description: 'Nombre del cliente' },
    { name: 'changed_fields', description: 'Campos modificados' },
    { name: 'next_execution', description: 'Próxima fecha prevista' },
    { name: 'manage_url', description: 'Link de autogestión' },
  ],
  'recurring-renewal-upcoming': [
    { name: 'customer_name', description: 'Nombre del cliente' },
    { name: 'frequency_label', description: 'Frecuencia contratada' },
    { name: 'total', description: 'Total cotizado' },
    { name: 'currency_code', description: 'Moneda' },
    { name: 'savings', description: 'Ahorro aplicado' },
    { name: 'price_warning', description: 'Aviso de variación de precio' },
  ],
  'recurring-stock-unavailable': [
    { name: 'recurring_order_id', description: 'ID de la suscripción' },
    { name: 'cycle_id', description: 'ID del ciclo' },
    { name: 'retry_at', description: 'Próximo reintento' },
    { name: 'retry_until', description: 'Fin de los reintentos' },
  ],
  'recurring-stock-skipped': [
    { name: 'recurring_order_id', description: 'ID de la suscripción' },
    { name: 'cycle_id', description: 'ID del ciclo omitido' },
  ],
  'recurring-payment-failed': [
    { name: 'recurring_order_id', description: 'ID de la suscripción' },
    { name: 'cycle_id', description: 'ID del ciclo' },
    { name: 'manage_url', description: 'Link seguro a la cuenta del cliente' },
  ],
  'recurring-stock-alert': [
    { name: 'variant_id', description: 'ID de la variante' },
    { name: 'available', description: 'Stock disponible neto' },
    { name: 'required_14d', description: 'Demanda a 14 días' },
    { name: 'required_30d', description: 'Demanda a 30 días' },
    { name: 'deficit_14d', description: 'Déficit a 14 días' },
    { name: 'deficit_30d', description: 'Déficit a 30 días' },
  ],

  // Gift Card Experience: las seis comparten plantilla y variables — en el seed
  // salen de un factory (`giftCardSeed`), no de entradas sueltas.
  'gift-card-delivery': [
    { name: 'landing_url', description: 'Enlace seguro de recepción' },
    { name: 'value', description: 'Valor acreditado' },
    { name: 'currency_code', description: 'Moneda' },
    { name: 'sender_name', description: 'Remitente visible' },
    { name: 'message', description: 'Mensaje del regalo' },
    { name: 'wallet_url', description: 'Enlace a la billetera del cliente' },
    { name: 'merchandising_url', description: 'Destino de recomendaciones' },
    { name: 'balance', description: 'Saldo atribuido disponible' },
    { name: 'days_remaining', description: 'Días restantes para reclamar' },
  ],
  'gift-card-resend': [
    { name: 'landing_url', description: 'Enlace seguro de recepción' },
    { name: 'value', description: 'Valor acreditado' },
    { name: 'currency_code', description: 'Moneda' },
    { name: 'sender_name', description: 'Remitente visible' },
    { name: 'message', description: 'Mensaje del regalo' },
    { name: 'wallet_url', description: 'Enlace a la billetera del cliente' },
    { name: 'merchandising_url', description: 'Destino de recomendaciones' },
    { name: 'balance', description: 'Saldo atribuido disponible' },
    { name: 'days_remaining', description: 'Días restantes para reclamar' },
  ],
  'gift-card-delivery-failed-buyer': [
    { name: 'landing_url', description: 'Enlace seguro de recepción' },
    { name: 'value', description: 'Valor acreditado' },
    { name: 'currency_code', description: 'Moneda' },
    { name: 'sender_name', description: 'Remitente visible' },
    { name: 'message', description: 'Mensaje del regalo' },
    { name: 'wallet_url', description: 'Enlace a la billetera del cliente' },
    { name: 'merchandising_url', description: 'Destino de recomendaciones' },
    { name: 'balance', description: 'Saldo atribuido disponible' },
    { name: 'days_remaining', description: 'Días restantes para reclamar' },
  ],
  'gift-card-claimed': [
    { name: 'landing_url', description: 'Enlace seguro de recepción' },
    { name: 'value', description: 'Valor acreditado' },
    { name: 'currency_code', description: 'Moneda' },
    { name: 'sender_name', description: 'Remitente visible' },
    { name: 'message', description: 'Mensaje del regalo' },
    { name: 'wallet_url', description: 'Enlace a la billetera del cliente' },
    { name: 'merchandising_url', description: 'Destino de recomendaciones' },
    { name: 'balance', description: 'Saldo atribuido disponible' },
    { name: 'days_remaining', description: 'Días restantes para reclamar' },
  ],
  'gift-card-balance-reminder': [
    { name: 'landing_url', description: 'Enlace seguro de recepción' },
    { name: 'value', description: 'Valor acreditado' },
    { name: 'currency_code', description: 'Moneda' },
    { name: 'sender_name', description: 'Remitente visible' },
    { name: 'message', description: 'Mensaje del regalo' },
    { name: 'wallet_url', description: 'Enlace a la billetera del cliente' },
    { name: 'merchandising_url', description: 'Destino de recomendaciones' },
    { name: 'balance', description: 'Saldo atribuido disponible' },
    { name: 'days_remaining', description: 'Días restantes para reclamar' },
  ],
  'gift-card-expiring': [
    { name: 'landing_url', description: 'Enlace seguro de recepción' },
    { name: 'value', description: 'Valor acreditado' },
    { name: 'currency_code', description: 'Moneda' },
    { name: 'sender_name', description: 'Remitente visible' },
    { name: 'message', description: 'Mensaje del regalo' },
    { name: 'wallet_url', description: 'Enlace a la billetera del cliente' },
    { name: 'merchandising_url', description: 'Destino de recomendaciones' },
    { name: 'balance', description: 'Saldo atribuido disponible' },
    { name: 'days_remaining', description: 'Días restantes para reclamar' },
  ],
};

/**
 * Las variables declaradas para una `key`, o `[]` si la plantilla no está en el
 * catálogo. Devolver `[]` y no `undefined` es a propósito: el call site pinta una
 * lista, y una plantilla fuera del catálogo tiene que degradar a "sin variables
 * declaradas", no romper la pantalla.
 */
export function variablesForKey(key: string | undefined | null): EmailTemplateVariable[] {
  if (!key) return [];
  return EMAIL_TEMPLATE_VARIABLES[key] ?? [];
}
